ingress:
  hosts:
    - host: wct-app-test.vat4ng.saictechdemo.com
      paths:
        - "/"
  tls:
    - secretName: tls-wct-app-test.vat4ng.saictechdemo.com
      hosts:
        - wct-app-test.vat4ng.saictechdemo.com
